name: Laravel CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kodenya
    - uses: actions/checkout@v3

    # 2. Setup PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, dom, fileinfo, sqlite3
        coverage: xdebug

    # 3. Copy file .env
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # 4. Install Dependency (Composer)
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # 5. Generate Application Key
    - name: Generate key
      run: php artisan key:generate

    # 6. Set Directory Permissions
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # 7. Create Database (SQLite)
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    # 8. Execute tests via PHPUnit
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
